version: "3.9"

services:
  redis:
    image: redis:latest
    networks:
      - fl-demo
  server:
    image: fl-demo-server:latest
    volumes:
      - /Users/musatai/masters/research/code/fl-demo/databases:/app/local_data
    environment:
      - C=1
      - K=4
      - E=20
    ports:
      - 8000:8000
    networks:
      - fl-demo
  client_1:
    image: fl-demo-client:latest
    volumes:
      - /Users/musatai/masters/research/code/fl-demo/databases:/app/local_data
    environment:
      - CLIENT_ID=1
    networks:
      - fl-demo
  client_2:
    image: fl-demo-client:latest
    volumes:
      - /Users/musatai/masters/research/code/fl-demo/databases:/app/local_data
    environment:
      - CLIENT_ID=2
    networks:
      - fl-demo
  client_3:
    image: fl-demo-client:latest
    volumes:
      - /Users/musatai/masters/research/code/fl-demo/databases:/app/local_data
    environment:
      - CLIENT_ID=3
    networks:
      - fl-demo
  client_4:
    image: fl-demo-client:latest
    volumes:
      - /Users/musatai/masters/research/code/fl-demo/databases:/app/local_data
    environment:
      - CLIENT_ID=4
    networks:
      - fl-demo

networks:
  fl-demo:
    name: fl-demo